# Generated by Django 4.1 on 2022-09-19 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'images_title',
            },
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'seo_block',
            },
        ),
        migrations.CreateModel(
            name='NewsAndPromotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('data_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(upload_to='images/')),
                ('link', models.URLField()),
                ('collection_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.imagestitle')),
                ('seo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.seoblock')),
            ],
            options={
                'db_table': 'news_and_promotions',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='gallery/')),
                ('collection_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.imagestitle')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
