# Generated by Django 4.1 on 2022-10-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='coordinates',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='coordinates_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='coordinates_uk',
            field=models.URLField(blank=True, null=True),
        ),
    ]
