# Generated by Django 4.1 on 2022-10-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='address_uk',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='coordinates_en',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='coordinates_uk',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='contactpagemodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='contactpagemodel',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='images',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='images',
            name='text_uk',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='seo_description_en',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='seo_description_uk',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='seo_keywords_en',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='seo_keywords_uk',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='seo_title_uk',
        ),
    ]
