# Generated by Django 4.1 on 2022-10-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_contactmodel_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='address_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='address_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='coordinates_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='coordinates_uk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='title_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
