# Generated by Django 4.1 on 2022-10-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_contactmodel_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/')),
                ('data_published', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'send_mail',
            },
        ),
    ]
