# Generated by Django 4.1 on 2022-10-26 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_sendmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmail',
            name='file',
            field=models.FileField(upload_to='file/', validators=[django.core.validators.FileExtensionValidator(['html'], message='file повинун бути html файл')]),
        ),
    ]
