# Generated by Django 4.1 on 2022-10-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_contactmodel_address_en_contactmodel_address_uk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagemodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='mainpagemodel',
            name='title_uk',
        ),
    ]
