# Generated by Django 4.1 on 2022-11-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_sendmail_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmail',
            name='choice_user',
            field=models.CharField(choices=[('Всі користувачі', 'Всі користувачі'), ('Вибрані', 'Вибрані')], default='Просто фон', max_length=20),
        ),
    ]
