# Generated by Django 4.1 on 2022-08-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('anonym', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adress', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=30)),
                ('language', models.BooleanField()),
                ('sex', models.BooleanField()),
                ('phone', models.CharField(max_length=13)),
                ('birthday', models.DateField()),
                ('choice_city', models.CharField(max_length=30)),
                ('repeat_password', models.CharField(max_length=20)),
            ],
        ),
    ]
